//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/access_key_type.proto

//go:build !protoopaque

package privatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An access key provides programmatic API access for a user.
type AccessKey struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier of the access key.
	Id       string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Specification of the access key.
	Spec *AccessKeySpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// Status of the access key.
	Status        *AccessKeyStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessKey) Reset() {
	*x = AccessKey{}
	mi := &file_osac_private_v1_access_key_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessKey) ProtoMessage() {}

func (x *AccessKey) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_access_key_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AccessKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccessKey) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AccessKey) GetSpec() *AccessKeySpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *AccessKey) GetStatus() *AccessKeyStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *AccessKey) SetId(v string) {
	x.Id = v
}

func (x *AccessKey) SetMetadata(v *Metadata) {
	x.Metadata = v
}

func (x *AccessKey) SetSpec(v *AccessKeySpec) {
	x.Spec = v
}

func (x *AccessKey) SetStatus(v *AccessKeyStatus) {
	x.Status = v
}

func (x *AccessKey) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *AccessKey) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.Spec != nil
}

func (x *AccessKey) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *AccessKey) ClearMetadata() {
	x.Metadata = nil
}

func (x *AccessKey) ClearSpec() {
	x.Spec = nil
}

func (x *AccessKey) ClearStatus() {
	x.Status = nil
}

type AccessKey_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the access key.
	Id       string
	Metadata *Metadata
	// Specification of the access key.
	Spec *AccessKeySpec
	// Status of the access key.
	Status *AccessKeyStatus
}

func (b0 AccessKey_builder) Build() *AccessKey {
	m0 := &AccessKey{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Metadata = b.Metadata
	x.Spec = b.Spec
	x.Status = b.Status
	return m0
}

// AccessKeySpec contains the desired state of the access key.
type AccessKeySpec struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// User ID that owns this access key.
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Organization ID.
	OrganizationId string `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	// Whether the access key is enabled.
	Enabled       bool `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessKeySpec) Reset() {
	*x = AccessKeySpec{}
	mi := &file_osac_private_v1_access_key_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessKeySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessKeySpec) ProtoMessage() {}

func (x *AccessKeySpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_access_key_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AccessKeySpec) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccessKeySpec) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *AccessKeySpec) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AccessKeySpec) SetUserId(v string) {
	x.UserId = v
}

func (x *AccessKeySpec) SetOrganizationId(v string) {
	x.OrganizationId = v
}

func (x *AccessKeySpec) SetEnabled(v bool) {
	x.Enabled = v
}

type AccessKeySpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// User ID that owns this access key.
	UserId string
	// Organization ID.
	OrganizationId string
	// Whether the access key is enabled.
	Enabled bool
}

func (b0 AccessKeySpec_builder) Build() *AccessKeySpec {
	m0 := &AccessKeySpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.UserId = b.UserId
	x.OrganizationId = b.OrganizationId
	x.Enabled = b.Enabled
	return m0
}

// AccessKeyStatus contains the observed state of the access key.
type AccessKeyStatus struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Phase         string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	LastUsedTime  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_used_time,json=lastUsedTime,proto3" json:"last_used_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessKeyStatus) Reset() {
	*x = AccessKeyStatus{}
	mi := &file_osac_private_v1_access_key_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessKeyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessKeyStatus) ProtoMessage() {}

func (x *AccessKeyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_access_key_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AccessKeyStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *AccessKeyStatus) GetLastUsedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedTime
	}
	return nil
}

func (x *AccessKeyStatus) SetPhase(v string) {
	x.Phase = v
}

func (x *AccessKeyStatus) SetLastUsedTime(v *timestamppb.Timestamp) {
	x.LastUsedTime = v
}

func (x *AccessKeyStatus) HasLastUsedTime() bool {
	if x == nil {
		return false
	}
	return x.LastUsedTime != nil
}

func (x *AccessKeyStatus) ClearLastUsedTime() {
	x.LastUsedTime = nil
}

type AccessKeyStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Phase        string
	LastUsedTime *timestamppb.Timestamp
}

func (b0 AccessKeyStatus_builder) Build() *AccessKeyStatus {
	m0 := &AccessKeyStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.Phase = b.Phase
	x.LastUsedTime = b.LastUsedTime
	return m0
}

// AccessKeyCredentials contains the secret credentials for an access key.
type AccessKeyCredentials struct {
	state           protoimpl.MessageState `protogen:"hybrid.v1"`
	AccessKeyId     string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	SecretAccessKey string                 `protobuf:"bytes,2,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccessKeyCredentials) Reset() {
	*x = AccessKeyCredentials{}
	mi := &file_osac_private_v1_access_key_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessKeyCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessKeyCredentials) ProtoMessage() {}

func (x *AccessKeyCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_access_key_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AccessKeyCredentials) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *AccessKeyCredentials) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *AccessKeyCredentials) SetAccessKeyId(v string) {
	x.AccessKeyId = v
}

func (x *AccessKeyCredentials) SetSecretAccessKey(v string) {
	x.SecretAccessKey = v
}

type AccessKeyCredentials_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AccessKeyId     string
	SecretAccessKey string
}

func (b0 AccessKeyCredentials_builder) Build() *AccessKeyCredentials {
	m0 := &AccessKeyCredentials{}
	b, x := &b0, m0
	_, _ = b, x
	x.AccessKeyId = b.AccessKeyId
	x.SecretAccessKey = b.SecretAccessKey
	return m0
}

var File_osac_private_v1_access_key_type_proto protoreflect.FileDescriptor

var file_osac_private_v1_access_key_type_proto_rawDesc = string([]byte{
	0x0a, 0x25, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x23, 0x6f, 0x73, 0x61, 0x63, 0x2f,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc0,
	0x01, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x32, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x53, 0x70, 0x65,
	0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x38, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x4b, 0x65, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x6b, 0x0a, 0x0d, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x53, 0x70,
	0x65, 0x63, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x6f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x69,
	0x0a, 0x0f, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x5f,
	0x75, 0x73, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x6c, 0x61, 0x73,
	0x74, 0x55, 0x73, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x66, 0x0a, 0x14, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x73, 0x12, 0x22, 0x0a, 0x0d, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6b, 0x65, 0x79, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x4b, 0x65, 0x79, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x5f,
	0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65,
	0x79, 0x42, 0xd7, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x12, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63,
	0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03,
	0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x4f, 0x73, 0x61, 0x63, 0x5c,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var file_osac_private_v1_access_key_type_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_osac_private_v1_access_key_type_proto_goTypes = []any{
	(*AccessKey)(nil),             // 0: osac.private.v1.AccessKey
	(*AccessKeySpec)(nil),         // 1: osac.private.v1.AccessKeySpec
	(*AccessKeyStatus)(nil),       // 2: osac.private.v1.AccessKeyStatus
	(*AccessKeyCredentials)(nil),  // 3: osac.private.v1.AccessKeyCredentials
	(*Metadata)(nil),              // 4: osac.private.v1.Metadata
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_osac_private_v1_access_key_type_proto_depIdxs = []int32{
	4, // 0: osac.private.v1.AccessKey.metadata:type_name -> osac.private.v1.Metadata
	1, // 1: osac.private.v1.AccessKey.spec:type_name -> osac.private.v1.AccessKeySpec
	2, // 2: osac.private.v1.AccessKey.status:type_name -> osac.private.v1.AccessKeyStatus
	5, // 3: osac.private.v1.AccessKeyStatus.last_used_time:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_osac_private_v1_access_key_type_proto_init() }
func file_osac_private_v1_access_key_type_proto_init() {
	if File_osac_private_v1_access_key_type_proto != nil {
		return
	}
	file_osac_private_v1_metadata_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_access_key_type_proto_rawDesc), len(file_osac_private_v1_access_key_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_private_v1_access_key_type_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_access_key_type_proto_depIdxs,
		MessageInfos:      file_osac_private_v1_access_key_type_proto_msgTypes,
	}.Build()
	File_osac_private_v1_access_key_type_proto = out.File
	file_osac_private_v1_access_key_type_proto_goTypes = nil
	file_osac_private_v1_access_key_type_proto_depIdxs = nil
}
