//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/private/v1/access_keys_service.proto

package privatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccessKeys_List_FullMethodName    = "/osac.private.v1.AccessKeys/List"
	AccessKeys_Get_FullMethodName     = "/osac.private.v1.AccessKeys/Get"
	AccessKeys_Create_FullMethodName  = "/osac.private.v1.AccessKeys/Create"
	AccessKeys_Disable_FullMethodName = "/osac.private.v1.AccessKeys/Disable"
	AccessKeys_Enable_FullMethodName  = "/osac.private.v1.AccessKeys/Enable"
	AccessKeys_Delete_FullMethodName  = "/osac.private.v1.AccessKeys/Delete"
	AccessKeys_Signal_FullMethodName  = "/osac.private.v1.AccessKeys/Signal"
)

// AccessKeysClient is the client API for AccessKeys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccessKeysClient interface {
	List(ctx context.Context, in *AccessKeysListRequest, opts ...grpc.CallOption) (*AccessKeysListResponse, error)
	Get(ctx context.Context, in *AccessKeysGetRequest, opts ...grpc.CallOption) (*AccessKeysGetResponse, error)
	Create(ctx context.Context, in *AccessKeysCreateRequest, opts ...grpc.CallOption) (*AccessKeysCreateResponse, error)
	Disable(ctx context.Context, in *AccessKeysDisableRequest, opts ...grpc.CallOption) (*AccessKeysDisableResponse, error)
	Enable(ctx context.Context, in *AccessKeysEnableRequest, opts ...grpc.CallOption) (*AccessKeysEnableResponse, error)
	Delete(ctx context.Context, in *AccessKeysDeleteRequest, opts ...grpc.CallOption) (*AccessKeysDeleteResponse, error)
	Signal(ctx context.Context, in *AccessKeysSignalRequest, opts ...grpc.CallOption) (*AccessKeysSignalResponse, error)
}

type accessKeysClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessKeysClient(cc grpc.ClientConnInterface) AccessKeysClient {
	return &accessKeysClient{cc}
}

func (c *accessKeysClient) List(ctx context.Context, in *AccessKeysListRequest, opts ...grpc.CallOption) (*AccessKeysListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessKeysListResponse)
	err := c.cc.Invoke(ctx, AccessKeys_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessKeysClient) Get(ctx context.Context, in *AccessKeysGetRequest, opts ...grpc.CallOption) (*AccessKeysGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessKeysGetResponse)
	err := c.cc.Invoke(ctx, AccessKeys_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessKeysClient) Create(ctx context.Context, in *AccessKeysCreateRequest, opts ...grpc.CallOption) (*AccessKeysCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessKeysCreateResponse)
	err := c.cc.Invoke(ctx, AccessKeys_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessKeysClient) Disable(ctx context.Context, in *AccessKeysDisableRequest, opts ...grpc.CallOption) (*AccessKeysDisableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessKeysDisableResponse)
	err := c.cc.Invoke(ctx, AccessKeys_Disable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessKeysClient) Enable(ctx context.Context, in *AccessKeysEnableRequest, opts ...grpc.CallOption) (*AccessKeysEnableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessKeysEnableResponse)
	err := c.cc.Invoke(ctx, AccessKeys_Enable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessKeysClient) Delete(ctx context.Context, in *AccessKeysDeleteRequest, opts ...grpc.CallOption) (*AccessKeysDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessKeysDeleteResponse)
	err := c.cc.Invoke(ctx, AccessKeys_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessKeysClient) Signal(ctx context.Context, in *AccessKeysSignalRequest, opts ...grpc.CallOption) (*AccessKeysSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessKeysSignalResponse)
	err := c.cc.Invoke(ctx, AccessKeys_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessKeysServer is the server API for AccessKeys service.
// All implementations must embed UnimplementedAccessKeysServer
// for forward compatibility.
type AccessKeysServer interface {
	List(context.Context, *AccessKeysListRequest) (*AccessKeysListResponse, error)
	Get(context.Context, *AccessKeysGetRequest) (*AccessKeysGetResponse, error)
	Create(context.Context, *AccessKeysCreateRequest) (*AccessKeysCreateResponse, error)
	Disable(context.Context, *AccessKeysDisableRequest) (*AccessKeysDisableResponse, error)
	Enable(context.Context, *AccessKeysEnableRequest) (*AccessKeysEnableResponse, error)
	Delete(context.Context, *AccessKeysDeleteRequest) (*AccessKeysDeleteResponse, error)
	Signal(context.Context, *AccessKeysSignalRequest) (*AccessKeysSignalResponse, error)
	mustEmbedUnimplementedAccessKeysServer()
}

// UnimplementedAccessKeysServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccessKeysServer struct{}

func (UnimplementedAccessKeysServer) List(context.Context, *AccessKeysListRequest) (*AccessKeysListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAccessKeysServer) Get(context.Context, *AccessKeysGetRequest) (*AccessKeysGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAccessKeysServer) Create(context.Context, *AccessKeysCreateRequest) (*AccessKeysCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAccessKeysServer) Disable(context.Context, *AccessKeysDisableRequest) (*AccessKeysDisableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disable not implemented")
}
func (UnimplementedAccessKeysServer) Enable(context.Context, *AccessKeysEnableRequest) (*AccessKeysEnableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enable not implemented")
}
func (UnimplementedAccessKeysServer) Delete(context.Context, *AccessKeysDeleteRequest) (*AccessKeysDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAccessKeysServer) Signal(context.Context, *AccessKeysSignalRequest) (*AccessKeysSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedAccessKeysServer) mustEmbedUnimplementedAccessKeysServer() {}
func (UnimplementedAccessKeysServer) testEmbeddedByValue()                    {}

// UnsafeAccessKeysServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessKeysServer will
// result in compilation errors.
type UnsafeAccessKeysServer interface {
	mustEmbedUnimplementedAccessKeysServer()
}

func RegisterAccessKeysServer(s grpc.ServiceRegistrar, srv AccessKeysServer) {
	// If the following call pancis, it indicates UnimplementedAccessKeysServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccessKeys_ServiceDesc, srv)
}

func _AccessKeys_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessKeysListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessKeysServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessKeys_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessKeysServer).List(ctx, req.(*AccessKeysListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessKeys_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessKeysGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessKeysServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessKeys_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessKeysServer).Get(ctx, req.(*AccessKeysGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessKeys_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessKeysCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessKeysServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessKeys_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessKeysServer).Create(ctx, req.(*AccessKeysCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessKeys_Disable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessKeysDisableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessKeysServer).Disable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessKeys_Disable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessKeysServer).Disable(ctx, req.(*AccessKeysDisableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessKeys_Enable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessKeysEnableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessKeysServer).Enable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessKeys_Enable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessKeysServer).Enable(ctx, req.(*AccessKeysEnableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessKeys_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessKeysDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessKeysServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessKeys_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessKeysServer).Delete(ctx, req.(*AccessKeysDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessKeys_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessKeysSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessKeysServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessKeys_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessKeysServer).Signal(ctx, req.(*AccessKeysSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessKeys_ServiceDesc is the grpc.ServiceDesc for AccessKeys service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessKeys_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.private.v1.AccessKeys",
	HandlerType: (*AccessKeysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AccessKeys_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AccessKeys_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _AccessKeys_Create_Handler,
		},
		{
			MethodName: "Disable",
			Handler:    _AccessKeys_Disable_Handler,
		},
		{
			MethodName: "Enable",
			Handler:    _AccessKeys_Enable_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AccessKeys_Delete_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _AccessKeys_Signal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/private/v1/access_keys_service.proto",
}
