//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/private/v1/capabilities_service.proto

package privatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Capabilities_Get_FullMethodName = "/osac.private.v1.Capabilities/Get"
)

// CapabilitiesClient is the client API for Capabilities service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Provides information about the capabilities of the server, such as the list of trusted token issuers for
// authentication. This is the private API equivalent and requires authentication.
type CapabilitiesClient interface {
	// Returns the capabilities of the server, including the authentication configuration that clients need in order to
	// obtain access tokens.
	Get(ctx context.Context, in *CapabilitiesGetRequest, opts ...grpc.CallOption) (*CapabilitiesGetResponse, error)
}

type capabilitiesClient struct {
	cc grpc.ClientConnInterface
}

func NewCapabilitiesClient(cc grpc.ClientConnInterface) CapabilitiesClient {
	return &capabilitiesClient{cc}
}

func (c *capabilitiesClient) Get(ctx context.Context, in *CapabilitiesGetRequest, opts ...grpc.CallOption) (*CapabilitiesGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesGetResponse)
	err := c.cc.Invoke(ctx, Capabilities_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CapabilitiesServer is the server API for Capabilities service.
// All implementations must embed UnimplementedCapabilitiesServer
// for forward compatibility.
//
// Provides information about the capabilities of the server, such as the list of trusted token issuers for
// authentication. This is the private API equivalent and requires authentication.
type CapabilitiesServer interface {
	// Returns the capabilities of the server, including the authentication configuration that clients need in order to
	// obtain access tokens.
	Get(context.Context, *CapabilitiesGetRequest) (*CapabilitiesGetResponse, error)
	mustEmbedUnimplementedCapabilitiesServer()
}

// UnimplementedCapabilitiesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCapabilitiesServer struct{}

func (UnimplementedCapabilitiesServer) Get(context.Context, *CapabilitiesGetRequest) (*CapabilitiesGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCapabilitiesServer) mustEmbedUnimplementedCapabilitiesServer() {}
func (UnimplementedCapabilitiesServer) testEmbeddedByValue()                      {}

// UnsafeCapabilitiesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapabilitiesServer will
// result in compilation errors.
type UnsafeCapabilitiesServer interface {
	mustEmbedUnimplementedCapabilitiesServer()
}

func RegisterCapabilitiesServer(s grpc.ServiceRegistrar, srv CapabilitiesServer) {
	// If the following call pancis, it indicates UnimplementedCapabilitiesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Capabilities_ServiceDesc, srv)
}

func _Capabilities_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilitiesGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilitiesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Capabilities_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilitiesServer).Get(ctx, req.(*CapabilitiesGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Capabilities_ServiceDesc is the grpc.ServiceDesc for Capabilities service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Capabilities_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.private.v1.Capabilities",
	HandlerType: (*CapabilitiesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Capabilities_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/private/v1/capabilities_service.proto",
}
