//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/private/v1/host_types_service.proto

package privatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostTypes_List_FullMethodName   = "/osac.private.v1.HostTypes/List"
	HostTypes_Get_FullMethodName    = "/osac.private.v1.HostTypes/Get"
	HostTypes_Create_FullMethodName = "/osac.private.v1.HostTypes/Create"
	HostTypes_Update_FullMethodName = "/osac.private.v1.HostTypes/Update"
	HostTypes_Delete_FullMethodName = "/osac.private.v1.HostTypes/Delete"
	HostTypes_Signal_FullMethodName = "/osac.private.v1.HostTypes/Signal"
)

// HostTypesClient is the client API for HostTypes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostTypesClient interface {
	List(ctx context.Context, in *HostTypesListRequest, opts ...grpc.CallOption) (*HostTypesListResponse, error)
	Get(ctx context.Context, in *HostTypesGetRequest, opts ...grpc.CallOption) (*HostTypesGetResponse, error)
	Create(ctx context.Context, in *HostTypesCreateRequest, opts ...grpc.CallOption) (*HostTypesCreateResponse, error)
	Update(ctx context.Context, in *HostTypesUpdateRequest, opts ...grpc.CallOption) (*HostTypesUpdateResponse, error)
	Delete(ctx context.Context, in *HostTypesDeleteRequest, opts ...grpc.CallOption) (*HostTypesDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(ctx context.Context, in *HostTypesSignalRequest, opts ...grpc.CallOption) (*HostTypesSignalResponse, error)
}

type hostTypesClient struct {
	cc grpc.ClientConnInterface
}

func NewHostTypesClient(cc grpc.ClientConnInterface) HostTypesClient {
	return &hostTypesClient{cc}
}

func (c *hostTypesClient) List(ctx context.Context, in *HostTypesListRequest, opts ...grpc.CallOption) (*HostTypesListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostTypesListResponse)
	err := c.cc.Invoke(ctx, HostTypes_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostTypesClient) Get(ctx context.Context, in *HostTypesGetRequest, opts ...grpc.CallOption) (*HostTypesGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostTypesGetResponse)
	err := c.cc.Invoke(ctx, HostTypes_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostTypesClient) Create(ctx context.Context, in *HostTypesCreateRequest, opts ...grpc.CallOption) (*HostTypesCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostTypesCreateResponse)
	err := c.cc.Invoke(ctx, HostTypes_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostTypesClient) Update(ctx context.Context, in *HostTypesUpdateRequest, opts ...grpc.CallOption) (*HostTypesUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostTypesUpdateResponse)
	err := c.cc.Invoke(ctx, HostTypes_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostTypesClient) Delete(ctx context.Context, in *HostTypesDeleteRequest, opts ...grpc.CallOption) (*HostTypesDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostTypesDeleteResponse)
	err := c.cc.Invoke(ctx, HostTypes_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostTypesClient) Signal(ctx context.Context, in *HostTypesSignalRequest, opts ...grpc.CallOption) (*HostTypesSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostTypesSignalResponse)
	err := c.cc.Invoke(ctx, HostTypes_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostTypesServer is the server API for HostTypes service.
// All implementations must embed UnimplementedHostTypesServer
// for forward compatibility.
type HostTypesServer interface {
	List(context.Context, *HostTypesListRequest) (*HostTypesListResponse, error)
	Get(context.Context, *HostTypesGetRequest) (*HostTypesGetResponse, error)
	Create(context.Context, *HostTypesCreateRequest) (*HostTypesCreateResponse, error)
	Update(context.Context, *HostTypesUpdateRequest) (*HostTypesUpdateResponse, error)
	Delete(context.Context, *HostTypesDeleteRequest) (*HostTypesDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(context.Context, *HostTypesSignalRequest) (*HostTypesSignalResponse, error)
	mustEmbedUnimplementedHostTypesServer()
}

// UnimplementedHostTypesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostTypesServer struct{}

func (UnimplementedHostTypesServer) List(context.Context, *HostTypesListRequest) (*HostTypesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedHostTypesServer) Get(context.Context, *HostTypesGetRequest) (*HostTypesGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedHostTypesServer) Create(context.Context, *HostTypesCreateRequest) (*HostTypesCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedHostTypesServer) Update(context.Context, *HostTypesUpdateRequest) (*HostTypesUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedHostTypesServer) Delete(context.Context, *HostTypesDeleteRequest) (*HostTypesDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedHostTypesServer) Signal(context.Context, *HostTypesSignalRequest) (*HostTypesSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedHostTypesServer) mustEmbedUnimplementedHostTypesServer() {}
func (UnimplementedHostTypesServer) testEmbeddedByValue()                   {}

// UnsafeHostTypesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostTypesServer will
// result in compilation errors.
type UnsafeHostTypesServer interface {
	mustEmbedUnimplementedHostTypesServer()
}

func RegisterHostTypesServer(s grpc.ServiceRegistrar, srv HostTypesServer) {
	// If the following call pancis, it indicates UnimplementedHostTypesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostTypes_ServiceDesc, srv)
}

func _HostTypes_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostTypesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostTypesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostTypes_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostTypesServer).List(ctx, req.(*HostTypesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostTypes_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostTypesGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostTypesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostTypes_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostTypesServer).Get(ctx, req.(*HostTypesGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostTypes_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostTypesCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostTypesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostTypes_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostTypesServer).Create(ctx, req.(*HostTypesCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostTypes_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostTypesUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostTypesServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostTypes_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostTypesServer).Update(ctx, req.(*HostTypesUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostTypes_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostTypesDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostTypesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostTypes_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostTypesServer).Delete(ctx, req.(*HostTypesDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostTypes_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostTypesSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostTypesServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostTypes_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostTypesServer).Signal(ctx, req.(*HostTypesSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostTypes_ServiceDesc is the grpc.ServiceDesc for HostTypes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostTypes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.private.v1.HostTypes",
	HandlerType: (*HostTypesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _HostTypes_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _HostTypes_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _HostTypes_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _HostTypes_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _HostTypes_Delete_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _HostTypes_Signal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/private/v1/host_types_service.proto",
}
