//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/lease_type.proto

//go:build !protoopaque

package privatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lease is a coordination primitive used to implement distributed leader election, allowing multiple instances of a
// component to run while ensuring only one is actively performing work at any given time. The holder of the lease
// periodically renews it to signal liveness. If the holder fails to renew before the lease duration expires, another
// instance can take over.
type Lease struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier of the lease.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Metadata common to all objects.
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Specification of the lease.
	Spec          *LeaseSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lease) Reset() {
	*x = Lease{}
	mi := &file_osac_private_v1_lease_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease) ProtoMessage() {}

func (x *Lease) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_lease_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Lease) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lease) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Lease) GetSpec() *LeaseSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Lease) SetId(v string) {
	x.Id = v
}

func (x *Lease) SetMetadata(v *Metadata) {
	x.Metadata = v
}

func (x *Lease) SetSpec(v *LeaseSpec) {
	x.Spec = v
}

func (x *Lease) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *Lease) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.Spec != nil
}

func (x *Lease) ClearMetadata() {
	x.Metadata = nil
}

func (x *Lease) ClearSpec() {
	x.Spec = nil
}

type Lease_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the lease.
	Id string
	// Metadata common to all objects.
	Metadata *Metadata
	// Specification of the lease.
	Spec *LeaseSpec
}

func (b0 Lease_builder) Build() *Lease {
	m0 := &Lease{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Metadata = b.Metadata
	x.Spec = b.Spec
	return m0
}

// LeaseSpec contains the details of the lease.
type LeaseSpec struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Identity of the current holder of the lease. This is typically a unique identifier for the instance that holds
	// the lease, such as a hostname or a combination of hostname and process identifier.
	Holder string `protobuf:"bytes,1,opt,name=holder,proto3" json:"holder,omitempty"`
	// Duration that the lease is valid after its last renewal. If the holder fails to renew the lease within this
	// duration, the lease is considered expired and another instance may take over.
	Duration *durationpb.Duration `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	// Time when the current holder first acquired the lease.
	AcquireTimestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=acquire_timestamp,json=acquireTimestamp,proto3" json:"acquire_timestamp,omitempty"`
	// Time when the holder last renewed the lease. Other instances compare this time plus the lease duration against
	// the current time to determine if the lease has expired.
	RenewTimestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=renew_timestamp,json=renewTimestamp,proto3" json:"renew_timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LeaseSpec) Reset() {
	*x = LeaseSpec{}
	mi := &file_osac_private_v1_lease_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseSpec) ProtoMessage() {}

func (x *LeaseSpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_lease_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LeaseSpec) GetHolder() string {
	if x != nil {
		return x.Holder
	}
	return ""
}

func (x *LeaseSpec) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *LeaseSpec) GetAcquireTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.AcquireTimestamp
	}
	return nil
}

func (x *LeaseSpec) GetRenewTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.RenewTimestamp
	}
	return nil
}

func (x *LeaseSpec) SetHolder(v string) {
	x.Holder = v
}

func (x *LeaseSpec) SetDuration(v *durationpb.Duration) {
	x.Duration = v
}

func (x *LeaseSpec) SetAcquireTimestamp(v *timestamppb.Timestamp) {
	x.AcquireTimestamp = v
}

func (x *LeaseSpec) SetRenewTimestamp(v *timestamppb.Timestamp) {
	x.RenewTimestamp = v
}

func (x *LeaseSpec) HasDuration() bool {
	if x == nil {
		return false
	}
	return x.Duration != nil
}

func (x *LeaseSpec) HasAcquireTimestamp() bool {
	if x == nil {
		return false
	}
	return x.AcquireTimestamp != nil
}

func (x *LeaseSpec) HasRenewTimestamp() bool {
	if x == nil {
		return false
	}
	return x.RenewTimestamp != nil
}

func (x *LeaseSpec) ClearDuration() {
	x.Duration = nil
}

func (x *LeaseSpec) ClearAcquireTimestamp() {
	x.AcquireTimestamp = nil
}

func (x *LeaseSpec) ClearRenewTimestamp() {
	x.RenewTimestamp = nil
}

type LeaseSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Identity of the current holder of the lease. This is typically a unique identifier for the instance that holds
	// the lease, such as a hostname or a combination of hostname and process identifier.
	Holder string
	// Duration that the lease is valid after its last renewal. If the holder fails to renew the lease within this
	// duration, the lease is considered expired and another instance may take over.
	Duration *durationpb.Duration
	// Time when the current holder first acquired the lease.
	AcquireTimestamp *timestamppb.Timestamp
	// Time when the holder last renewed the lease. Other instances compare this time plus the lease duration against
	// the current time to determine if the lease has expired.
	RenewTimestamp *timestamppb.Timestamp
}

func (b0 LeaseSpec_builder) Build() *LeaseSpec {
	m0 := &LeaseSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.Holder = b.Holder
	x.Duration = b.Duration
	x.AcquireTimestamp = b.AcquireTimestamp
	x.RenewTimestamp = b.RenewTimestamp
	return m0
}

var File_osac_private_v1_lease_type_proto protoreflect.FileDescriptor

var file_osac_private_v1_lease_type_proto_rawDesc = string([]byte{
	0x0a, 0x20, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2e, 0x76, 0x31, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x23, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7e, 0x0a, 0x05, 0x4c, 0x65, 0x61,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2e, 0x0a, 0x04, 0x73, 0x70, 0x65,
	0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x53,
	0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x22, 0xe8, 0x01, 0x0a, 0x09, 0x4c, 0x65,
	0x61, 0x73, 0x65, 0x53, 0x70, 0x65, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x6c, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x12,
	0x35, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x47, 0x0a, 0x11, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72,
	0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x10, 0x61,
	0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x43, 0x0a, 0x0f, 0x72, 0x65, 0x6e, 0x65, 0x77, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x72, 0x65, 0x6e, 0x65, 0x77, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x42, 0xd3, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61,
	0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x0e, 0x4c, 0x65,
	0x61, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4c,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f,
	0x76, 0x31, 0x3b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f,
	0x50, 0x58, 0xaa, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var file_osac_private_v1_lease_type_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_osac_private_v1_lease_type_proto_goTypes = []any{
	(*Lease)(nil),                 // 0: osac.private.v1.Lease
	(*LeaseSpec)(nil),             // 1: osac.private.v1.LeaseSpec
	(*Metadata)(nil),              // 2: osac.private.v1.Metadata
	(*durationpb.Duration)(nil),   // 3: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_osac_private_v1_lease_type_proto_depIdxs = []int32{
	2, // 0: osac.private.v1.Lease.metadata:type_name -> osac.private.v1.Metadata
	1, // 1: osac.private.v1.Lease.spec:type_name -> osac.private.v1.LeaseSpec
	3, // 2: osac.private.v1.LeaseSpec.duration:type_name -> google.protobuf.Duration
	4, // 3: osac.private.v1.LeaseSpec.acquire_timestamp:type_name -> google.protobuf.Timestamp
	4, // 4: osac.private.v1.LeaseSpec.renew_timestamp:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_osac_private_v1_lease_type_proto_init() }
func file_osac_private_v1_lease_type_proto_init() {
	if File_osac_private_v1_lease_type_proto != nil {
		return
	}
	file_osac_private_v1_metadata_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_lease_type_proto_rawDesc), len(file_osac_private_v1_lease_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_private_v1_lease_type_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_lease_type_proto_depIdxs,
		MessageInfos:      file_osac_private_v1_lease_type_proto_msgTypes,
	}.Build()
	File_osac_private_v1_lease_type_proto = out.File
	file_osac_private_v1_lease_type_proto_goTypes = nil
	file_osac_private_v1_lease_type_proto_depIdxs = nil
}
