//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/private/v1/leases_service.proto

package privatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Leases_List_FullMethodName   = "/osac.private.v1.Leases/List"
	Leases_Get_FullMethodName    = "/osac.private.v1.Leases/Get"
	Leases_Create_FullMethodName = "/osac.private.v1.Leases/Create"
	Leases_Delete_FullMethodName = "/osac.private.v1.Leases/Delete"
	Leases_Update_FullMethodName = "/osac.private.v1.Leases/Update"
	Leases_Signal_FullMethodName = "/osac.private.v1.Leases/Signal"
)

// LeasesClient is the client API for Leases service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Leases provides operations for managing lease objects used for distributed coordination such as leader election.
type LeasesClient interface {
	// List returns a paginated list of leases, optionally filtered by a CEL expression.
	List(ctx context.Context, in *LeasesListRequest, opts ...grpc.CallOption) (*LeasesListResponse, error)
	// Get returns a single lease by its identifier.
	Get(ctx context.Context, in *LeasesGetRequest, opts ...grpc.CallOption) (*LeasesGetResponse, error)
	// Create creates a new lease.
	Create(ctx context.Context, in *LeasesCreateRequest, opts ...grpc.CallOption) (*LeasesCreateResponse, error)
	// Delete deletes a lease by its identifier.
	Delete(ctx context.Context, in *LeasesDeleteRequest, opts ...grpc.CallOption) (*LeasesDeleteResponse, error)
	// Update updates an existing lease. The update mask controls which fields are modified.
	Update(ctx context.Context, in *LeasesUpdateRequest, opts ...grpc.CallOption) (*LeasesUpdateResponse, error)
	// Signal indicates that something changed in the lease or the system that may require reconciling the lease.
	Signal(ctx context.Context, in *LeasesSignalRequest, opts ...grpc.CallOption) (*LeasesSignalResponse, error)
}

type leasesClient struct {
	cc grpc.ClientConnInterface
}

func NewLeasesClient(cc grpc.ClientConnInterface) LeasesClient {
	return &leasesClient{cc}
}

func (c *leasesClient) List(ctx context.Context, in *LeasesListRequest, opts ...grpc.CallOption) (*LeasesListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeasesListResponse)
	err := c.cc.Invoke(ctx, Leases_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leasesClient) Get(ctx context.Context, in *LeasesGetRequest, opts ...grpc.CallOption) (*LeasesGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeasesGetResponse)
	err := c.cc.Invoke(ctx, Leases_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leasesClient) Create(ctx context.Context, in *LeasesCreateRequest, opts ...grpc.CallOption) (*LeasesCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeasesCreateResponse)
	err := c.cc.Invoke(ctx, Leases_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leasesClient) Delete(ctx context.Context, in *LeasesDeleteRequest, opts ...grpc.CallOption) (*LeasesDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeasesDeleteResponse)
	err := c.cc.Invoke(ctx, Leases_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leasesClient) Update(ctx context.Context, in *LeasesUpdateRequest, opts ...grpc.CallOption) (*LeasesUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeasesUpdateResponse)
	err := c.cc.Invoke(ctx, Leases_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leasesClient) Signal(ctx context.Context, in *LeasesSignalRequest, opts ...grpc.CallOption) (*LeasesSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeasesSignalResponse)
	err := c.cc.Invoke(ctx, Leases_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeasesServer is the server API for Leases service.
// All implementations must embed UnimplementedLeasesServer
// for forward compatibility.
//
// Leases provides operations for managing lease objects used for distributed coordination such as leader election.
type LeasesServer interface {
	// List returns a paginated list of leases, optionally filtered by a CEL expression.
	List(context.Context, *LeasesListRequest) (*LeasesListResponse, error)
	// Get returns a single lease by its identifier.
	Get(context.Context, *LeasesGetRequest) (*LeasesGetResponse, error)
	// Create creates a new lease.
	Create(context.Context, *LeasesCreateRequest) (*LeasesCreateResponse, error)
	// Delete deletes a lease by its identifier.
	Delete(context.Context, *LeasesDeleteRequest) (*LeasesDeleteResponse, error)
	// Update updates an existing lease. The update mask controls which fields are modified.
	Update(context.Context, *LeasesUpdateRequest) (*LeasesUpdateResponse, error)
	// Signal indicates that something changed in the lease or the system that may require reconciling the lease.
	Signal(context.Context, *LeasesSignalRequest) (*LeasesSignalResponse, error)
	mustEmbedUnimplementedLeasesServer()
}

// UnimplementedLeasesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeasesServer struct{}

func (UnimplementedLeasesServer) List(context.Context, *LeasesListRequest) (*LeasesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedLeasesServer) Get(context.Context, *LeasesGetRequest) (*LeasesGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedLeasesServer) Create(context.Context, *LeasesCreateRequest) (*LeasesCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedLeasesServer) Delete(context.Context, *LeasesDeleteRequest) (*LeasesDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedLeasesServer) Update(context.Context, *LeasesUpdateRequest) (*LeasesUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedLeasesServer) Signal(context.Context, *LeasesSignalRequest) (*LeasesSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedLeasesServer) mustEmbedUnimplementedLeasesServer() {}
func (UnimplementedLeasesServer) testEmbeddedByValue()                {}

// UnsafeLeasesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeasesServer will
// result in compilation errors.
type UnsafeLeasesServer interface {
	mustEmbedUnimplementedLeasesServer()
}

func RegisterLeasesServer(s grpc.ServiceRegistrar, srv LeasesServer) {
	// If the following call pancis, it indicates UnimplementedLeasesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Leases_ServiceDesc, srv)
}

func _Leases_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeasesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeasesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Leases_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeasesServer).List(ctx, req.(*LeasesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Leases_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeasesGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeasesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Leases_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeasesServer).Get(ctx, req.(*LeasesGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Leases_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeasesCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeasesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Leases_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeasesServer).Create(ctx, req.(*LeasesCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Leases_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeasesDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeasesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Leases_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeasesServer).Delete(ctx, req.(*LeasesDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Leases_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeasesUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeasesServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Leases_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeasesServer).Update(ctx, req.(*LeasesUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Leases_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeasesSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeasesServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Leases_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeasesServer).Signal(ctx, req.(*LeasesSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Leases_ServiceDesc is the grpc.ServiceDesc for Leases service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Leases_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.private.v1.Leases",
	HandlerType: (*LeasesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Leases_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Leases_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Leases_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Leases_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Leases_Update_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _Leases_Signal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/private/v1/leases_service.proto",
}
