//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/private/v1/organizations_service.proto

package privatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Organizations_List_FullMethodName   = "/osac.private.v1.Organizations/List"
	Organizations_Get_FullMethodName    = "/osac.private.v1.Organizations/Get"
	Organizations_Create_FullMethodName = "/osac.private.v1.Organizations/Create"
	Organizations_Delete_FullMethodName = "/osac.private.v1.Organizations/Delete"
	Organizations_Update_FullMethodName = "/osac.private.v1.Organizations/Update"
	Organizations_Signal_FullMethodName = "/osac.private.v1.Organizations/Signal"
)

// OrganizationsClient is the client API for Organizations service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrganizationsClient interface {
	List(ctx context.Context, in *OrganizationsListRequest, opts ...grpc.CallOption) (*OrganizationsListResponse, error)
	Get(ctx context.Context, in *OrganizationsGetRequest, opts ...grpc.CallOption) (*OrganizationsGetResponse, error)
	Create(ctx context.Context, in *OrganizationsCreateRequest, opts ...grpc.CallOption) (*OrganizationsCreateResponse, error)
	Delete(ctx context.Context, in *OrganizationsDeleteRequest, opts ...grpc.CallOption) (*OrganizationsDeleteResponse, error)
	Update(ctx context.Context, in *OrganizationsUpdateRequest, opts ...grpc.CallOption) (*OrganizationsUpdateResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(ctx context.Context, in *OrganizationsSignalRequest, opts ...grpc.CallOption) (*OrganizationsSignalResponse, error)
}

type organizationsClient struct {
	cc grpc.ClientConnInterface
}

func NewOrganizationsClient(cc grpc.ClientConnInterface) OrganizationsClient {
	return &organizationsClient{cc}
}

func (c *organizationsClient) List(ctx context.Context, in *OrganizationsListRequest, opts ...grpc.CallOption) (*OrganizationsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrganizationsListResponse)
	err := c.cc.Invoke(ctx, Organizations_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationsClient) Get(ctx context.Context, in *OrganizationsGetRequest, opts ...grpc.CallOption) (*OrganizationsGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrganizationsGetResponse)
	err := c.cc.Invoke(ctx, Organizations_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationsClient) Create(ctx context.Context, in *OrganizationsCreateRequest, opts ...grpc.CallOption) (*OrganizationsCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrganizationsCreateResponse)
	err := c.cc.Invoke(ctx, Organizations_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationsClient) Delete(ctx context.Context, in *OrganizationsDeleteRequest, opts ...grpc.CallOption) (*OrganizationsDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrganizationsDeleteResponse)
	err := c.cc.Invoke(ctx, Organizations_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationsClient) Update(ctx context.Context, in *OrganizationsUpdateRequest, opts ...grpc.CallOption) (*OrganizationsUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrganizationsUpdateResponse)
	err := c.cc.Invoke(ctx, Organizations_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationsClient) Signal(ctx context.Context, in *OrganizationsSignalRequest, opts ...grpc.CallOption) (*OrganizationsSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrganizationsSignalResponse)
	err := c.cc.Invoke(ctx, Organizations_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrganizationsServer is the server API for Organizations service.
// All implementations must embed UnimplementedOrganizationsServer
// for forward compatibility.
type OrganizationsServer interface {
	List(context.Context, *OrganizationsListRequest) (*OrganizationsListResponse, error)
	Get(context.Context, *OrganizationsGetRequest) (*OrganizationsGetResponse, error)
	Create(context.Context, *OrganizationsCreateRequest) (*OrganizationsCreateResponse, error)
	Delete(context.Context, *OrganizationsDeleteRequest) (*OrganizationsDeleteResponse, error)
	Update(context.Context, *OrganizationsUpdateRequest) (*OrganizationsUpdateResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(context.Context, *OrganizationsSignalRequest) (*OrganizationsSignalResponse, error)
	mustEmbedUnimplementedOrganizationsServer()
}

// UnimplementedOrganizationsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrganizationsServer struct{}

func (UnimplementedOrganizationsServer) List(context.Context, *OrganizationsListRequest) (*OrganizationsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedOrganizationsServer) Get(context.Context, *OrganizationsGetRequest) (*OrganizationsGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedOrganizationsServer) Create(context.Context, *OrganizationsCreateRequest) (*OrganizationsCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedOrganizationsServer) Delete(context.Context, *OrganizationsDeleteRequest) (*OrganizationsDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedOrganizationsServer) Update(context.Context, *OrganizationsUpdateRequest) (*OrganizationsUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedOrganizationsServer) Signal(context.Context, *OrganizationsSignalRequest) (*OrganizationsSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedOrganizationsServer) mustEmbedUnimplementedOrganizationsServer() {}
func (UnimplementedOrganizationsServer) testEmbeddedByValue()                       {}

// UnsafeOrganizationsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrganizationsServer will
// result in compilation errors.
type UnsafeOrganizationsServer interface {
	mustEmbedUnimplementedOrganizationsServer()
}

func RegisterOrganizationsServer(s grpc.ServiceRegistrar, srv OrganizationsServer) {
	// If the following call pancis, it indicates UnimplementedOrganizationsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Organizations_ServiceDesc, srv)
}

func _Organizations_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrganizationsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Organizations_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationsServer).List(ctx, req.(*OrganizationsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organizations_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrganizationsGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Organizations_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationsServer).Get(ctx, req.(*OrganizationsGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organizations_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrganizationsCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Organizations_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationsServer).Create(ctx, req.(*OrganizationsCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organizations_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrganizationsDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Organizations_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationsServer).Delete(ctx, req.(*OrganizationsDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organizations_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrganizationsUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Organizations_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationsServer).Update(ctx, req.(*OrganizationsUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organizations_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrganizationsSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationsServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Organizations_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationsServer).Signal(ctx, req.(*OrganizationsSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Organizations_ServiceDesc is the grpc.ServiceDesc for Organizations service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Organizations_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.private.v1.Organizations",
	HandlerType: (*OrganizationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Organizations_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Organizations_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Organizations_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Organizations_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Organizations_Update_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _Organizations_Signal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/private/v1/organizations_service.proto",
}
