//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/public_ips_service.proto

//go:build !protoopaque

package privatev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublicIPsListRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Index of the first result. If not specified the default value will be zero.
	Offset *int32 `protobuf:"varint,1,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	// Maximum number of results to be returned by the server. When not specified all the results will be returned. Note
	// that there may not be enough results to return, and that the server may decide, for performance reasons, to return
	// less results than requested.
	Limit *int32 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	// Filter criteria.
	//
	// The value of this parameter is a [CEL](https://cel.dev) expression used to select which objects to return. The
	// built-in `this` variable refers to the object being tested and `now` refers to the current date and time. If the
	// expression evaluates to `true` the object is included in the results. For example, to retrieve all public IPs
	// in ALLOCATED state:
	//
	//	this.status.state == PUBLIC_IP_STATE_ALLOCATED
	//
	// If this isn't provided, or if the value is empty, then all the public IPs that the user has permission to see
	// will be returned. Not all CEL constructs are currently supported for implementation reasons; see the filter
	// documentation (docs/FILTER.md) for the full details.
	Filter *string `protobuf:"bytes,3,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	// Order criteria.
	//
	// The syntax of this parameter is similar to the syntax of the _order by_ clause of a SQL statement, but using the
	// names of the attributes of the public IP instead of the names of the columns of a table. For example, in order
	// to sort the public IPs descending by creation time the value should be:
	//
	//	metadata.created_at desc
	//
	// If the parameter isn't provided, or if the value is empty, then the order of the results is undefined.
	Order         *string `protobuf:"bytes,4,opt,name=order,proto3,oneof" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicIPsListRequest) Reset() {
	*x = PublicIPsListRequest{}
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPsListRequest) ProtoMessage() {}

func (x *PublicIPsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicIPsListRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *PublicIPsListRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *PublicIPsListRequest) GetFilter() string {
	if x != nil && x.Filter != nil {
		return *x.Filter
	}
	return ""
}

func (x *PublicIPsListRequest) GetOrder() string {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return ""
}

func (x *PublicIPsListRequest) SetOffset(v int32) {
	x.Offset = &v
}

func (x *PublicIPsListRequest) SetLimit(v int32) {
	x.Limit = &v
}

func (x *PublicIPsListRequest) SetFilter(v string) {
	x.Filter = &v
}

func (x *PublicIPsListRequest) SetOrder(v string) {
	x.Order = &v
}

func (x *PublicIPsListRequest) HasOffset() bool {
	if x == nil {
		return false
	}
	return x.Offset != nil
}

func (x *PublicIPsListRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return x.Limit != nil
}

func (x *PublicIPsListRequest) HasFilter() bool {
	if x == nil {
		return false
	}
	return x.Filter != nil
}

func (x *PublicIPsListRequest) HasOrder() bool {
	if x == nil {
		return false
	}
	return x.Order != nil
}

func (x *PublicIPsListRequest) ClearOffset() {
	x.Offset = nil
}

func (x *PublicIPsListRequest) ClearLimit() {
	x.Limit = nil
}

func (x *PublicIPsListRequest) ClearFilter() {
	x.Filter = nil
}

func (x *PublicIPsListRequest) ClearOrder() {
	x.Order = nil
}

type PublicIPsListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Index of the first result. If not specified the default value will be zero.
	Offset *int32
	// Maximum number of results to be returned by the server. When not specified all the results will be returned. Note
	// that there may not be enough results to return, and that the server may decide, for performance reasons, to return
	// less results than requested.
	Limit *int32
	// Filter criteria.
	//
	// The value of this parameter is a [CEL](https://cel.dev) expression used to select which objects to return. The
	// built-in `this` variable refers to the object being tested and `now` refers to the current date and time. If the
	// expression evaluates to `true` the object is included in the results. For example, to retrieve all public IPs
	// in ALLOCATED state:
	//
	//	this.status.state == PUBLIC_IP_STATE_ALLOCATED
	//
	// If this isn't provided, or if the value is empty, then all the public IPs that the user has permission to see
	// will be returned. Not all CEL constructs are currently supported for implementation reasons; see the filter
	// documentation (docs/FILTER.md) for the full details.
	Filter *string
	// Order criteria.
	//
	// The syntax of this parameter is similar to the syntax of the _order by_ clause of a SQL statement, but using the
	// names of the attributes of the public IP instead of the names of the columns of a table. For example, in order
	// to sort the public IPs descending by creation time the value should be:
	//
	//	metadata.created_at desc
	//
	// If the parameter isn't provided, or if the value is empty, then the order of the results is undefined.
	Order *string
}

func (b0 PublicIPsListRequest_builder) Build() *PublicIPsListRequest {
	m0 := &PublicIPsListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Offset = b.Offset
	x.Limit = b.Limit
	x.Filter = b.Filter
	x.Order = b.Order
	return m0
}

type PublicIPsListResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Actual number of items returned. Note that this may be smaller than the value requested in the `limit` parameter
	// of the request if there are not enough items, or if the system decides that returning that number of items isn't
	// feasible or convenient for performance reasons.
	Size int32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// Total number of items of the collection that match the search criteria, regardless of the number of results
	// requested with the `limit` parameter.
	Total int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	// List of results.
	Items         []*PublicIP `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicIPsListResponse) Reset() {
	*x = PublicIPsListResponse{}
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPsListResponse) ProtoMessage() {}

func (x *PublicIPsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicIPsListResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PublicIPsListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PublicIPsListResponse) GetItems() []*PublicIP {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PublicIPsListResponse) SetSize(v int32) {
	x.Size = v
}

func (x *PublicIPsListResponse) SetTotal(v int32) {
	x.Total = v
}

func (x *PublicIPsListResponse) SetItems(v []*PublicIP) {
	x.Items = v
}

type PublicIPsListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Actual number of items returned. Note that this may be smaller than the value requested in the `limit` parameter
	// of the request if there are not enough items, or if the system decides that returning that number of items isn't
	// feasible or convenient for performance reasons.
	Size int32
	// Total number of items of the collection that match the search criteria, regardless of the number of results
	// requested with the `limit` parameter.
	Total int32
	// List of results.
	Items []*PublicIP
}

func (b0 PublicIPsListResponse_builder) Build() *PublicIPsListResponse {
	m0 := &PublicIPsListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Size = b.Size
	x.Total = b.Total
	x.Items = b.Items
	return m0
}

type PublicIPsGetRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicIPsGetRequest) Reset() {
	*x = PublicIPsGetRequest{}
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPsGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPsGetRequest) ProtoMessage() {}

func (x *PublicIPsGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicIPsGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublicIPsGetRequest) SetId(v string) {
	x.Id = v
}

type PublicIPsGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 PublicIPsGetRequest_builder) Build() *PublicIPsGetRequest {
	m0 := &PublicIPsGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	return m0
}

type PublicIPsGetResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Object        *PublicIP              `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicIPsGetResponse) Reset() {
	*x = PublicIPsGetResponse{}
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPsGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPsGetResponse) ProtoMessage() {}

func (x *PublicIPsGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicIPsGetResponse) GetObject() *PublicIP {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *PublicIPsGetResponse) SetObject(v *PublicIP) {
	x.Object = v
}

func (x *PublicIPsGetResponse) HasObject() bool {
	if x == nil {
		return false
	}
	return x.Object != nil
}

func (x *PublicIPsGetResponse) ClearObject() {
	x.Object = nil
}

type PublicIPsGetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Object *PublicIP
}

func (b0 PublicIPsGetResponse_builder) Build() *PublicIPsGetResponse {
	m0 := &PublicIPsGetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Object = b.Object
	return m0
}

type PublicIPsCreateRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Object        *PublicIP              `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicIPsCreateRequest) Reset() {
	*x = PublicIPsCreateRequest{}
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPsCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPsCreateRequest) ProtoMessage() {}

func (x *PublicIPsCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicIPsCreateRequest) GetObject() *PublicIP {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *PublicIPsCreateRequest) SetObject(v *PublicIP) {
	x.Object = v
}

func (x *PublicIPsCreateRequest) HasObject() bool {
	if x == nil {
		return false
	}
	return x.Object != nil
}

func (x *PublicIPsCreateRequest) ClearObject() {
	x.Object = nil
}

type PublicIPsCreateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Object *PublicIP
}

func (b0 PublicIPsCreateRequest_builder) Build() *PublicIPsCreateRequest {
	m0 := &PublicIPsCreateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Object = b.Object
	return m0
}

type PublicIPsCreateResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Object        *PublicIP              `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicIPsCreateResponse) Reset() {
	*x = PublicIPsCreateResponse{}
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPsCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPsCreateResponse) ProtoMessage() {}

func (x *PublicIPsCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicIPsCreateResponse) GetObject() *PublicIP {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *PublicIPsCreateResponse) SetObject(v *PublicIP) {
	x.Object = v
}

func (x *PublicIPsCreateResponse) HasObject() bool {
	if x == nil {
		return false
	}
	return x.Object != nil
}

func (x *PublicIPsCreateResponse) ClearObject() {
	x.Object = nil
}

type PublicIPsCreateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Object *PublicIP
}

func (b0 PublicIPsCreateResponse_builder) Build() *PublicIPsCreateResponse {
	m0 := &PublicIPsCreateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Object = b.Object
	return m0
}

type PublicIPsUpdateRequest struct {
	state      protoimpl.MessageState `protogen:"hybrid.v1"`
	Object     *PublicIP              `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	// Lock enables optimistic locking. When set to true, the server verifies that the current version of the object
	// matches the value of the metadata.version field of the submitted object. If they differ the update will be
	// rejected. This is useful to prevent lost updates when multiple clients are modifying the same object concurrently.
	Lock          bool `protobuf:"varint,3,opt,name=lock,proto3" json:"lock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicIPsUpdateRequest) Reset() {
	*x = PublicIPsUpdateRequest{}
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPsUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPsUpdateRequest) ProtoMessage() {}

func (x *PublicIPsUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicIPsUpdateRequest) GetObject() *PublicIP {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *PublicIPsUpdateRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *PublicIPsUpdateRequest) GetLock() bool {
	if x != nil {
		return x.Lock
	}
	return false
}

func (x *PublicIPsUpdateRequest) SetObject(v *PublicIP) {
	x.Object = v
}

func (x *PublicIPsUpdateRequest) SetUpdateMask(v *fieldmaskpb.FieldMask) {
	x.UpdateMask = v
}

func (x *PublicIPsUpdateRequest) SetLock(v bool) {
	x.Lock = v
}

func (x *PublicIPsUpdateRequest) HasObject() bool {
	if x == nil {
		return false
	}
	return x.Object != nil
}

func (x *PublicIPsUpdateRequest) HasUpdateMask() bool {
	if x == nil {
		return false
	}
	return x.UpdateMask != nil
}

func (x *PublicIPsUpdateRequest) ClearObject() {
	x.Object = nil
}

func (x *PublicIPsUpdateRequest) ClearUpdateMask() {
	x.UpdateMask = nil
}

type PublicIPsUpdateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Object     *PublicIP
	UpdateMask *fieldmaskpb.FieldMask
	// Lock enables optimistic locking. When set to true, the server verifies that the current version of the object
	// matches the value of the metadata.version field of the submitted object. If they differ the update will be
	// rejected. This is useful to prevent lost updates when multiple clients are modifying the same object concurrently.
	Lock bool
}

func (b0 PublicIPsUpdateRequest_builder) Build() *PublicIPsUpdateRequest {
	m0 := &PublicIPsUpdateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Object = b.Object
	x.UpdateMask = b.UpdateMask
	x.Lock = b.Lock
	return m0
}

type PublicIPsUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Object        *PublicIP              `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicIPsUpdateResponse) Reset() {
	*x = PublicIPsUpdateResponse{}
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPsUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPsUpdateResponse) ProtoMessage() {}

func (x *PublicIPsUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicIPsUpdateResponse) GetObject() *PublicIP {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *PublicIPsUpdateResponse) SetObject(v *PublicIP) {
	x.Object = v
}

func (x *PublicIPsUpdateResponse) HasObject() bool {
	if x == nil {
		return false
	}
	return x.Object != nil
}

func (x *PublicIPsUpdateResponse) ClearObject() {
	x.Object = nil
}

type PublicIPsUpdateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Object *PublicIP
}

func (b0 PublicIPsUpdateResponse_builder) Build() *PublicIPsUpdateResponse {
	m0 := &PublicIPsUpdateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Object = b.Object
	return m0
}

type PublicIPsDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicIPsDeleteRequest) Reset() {
	*x = PublicIPsDeleteRequest{}
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPsDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPsDeleteRequest) ProtoMessage() {}

func (x *PublicIPsDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicIPsDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublicIPsDeleteRequest) SetId(v string) {
	x.Id = v
}

type PublicIPsDeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 PublicIPsDeleteRequest_builder) Build() *PublicIPsDeleteRequest {
	m0 := &PublicIPsDeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	return m0
}

type PublicIPsDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicIPsDeleteResponse) Reset() {
	*x = PublicIPsDeleteResponse{}
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPsDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPsDeleteResponse) ProtoMessage() {}

func (x *PublicIPsDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PublicIPsDeleteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 PublicIPsDeleteResponse_builder) Build() *PublicIPsDeleteResponse {
	m0 := &PublicIPsDeleteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type PublicIPsSignalRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicIPsSignalRequest) Reset() {
	*x = PublicIPsSignalRequest{}
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPsSignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPsSignalRequest) ProtoMessage() {}

func (x *PublicIPsSignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicIPsSignalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublicIPsSignalRequest) SetId(v string) {
	x.Id = v
}

type PublicIPsSignalRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 PublicIPsSignalRequest_builder) Build() *PublicIPsSignalRequest {
	m0 := &PublicIPsSignalRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	return m0
}

type PublicIPsSignalResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicIPsSignalResponse) Reset() {
	*x = PublicIPsSignalResponse{}
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPsSignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPsSignalResponse) ProtoMessage() {}

func (x *PublicIPsSignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_public_ips_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type PublicIPsSignalResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 PublicIPsSignalResponse_builder) Build() *PublicIPsSignalResponse {
	m0 := &PublicIPsSignalResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_osac_private_v1_public_ips_service_proto protoreflect.FileDescriptor

var file_osac_private_v1_public_ips_service_proto_rawDesc = string([]byte{
	0x0a, 0x28, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x69, 0x70, 0x73, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x24, 0x6f, 0x73, 0x61,
	0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x5f, 0x69, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xb0, 0x01, 0x0a, 0x14, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x88,
	0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x02, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12,
	0x19, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03,
	0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x42,
	0x09, 0x0a, 0x07, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x22, 0x72, 0x0a, 0x15, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2f, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49,
	0x50, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x25, 0x0a, 0x13, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x49, 0x50, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x49, 0x0a, 0x14, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x73, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x49, 0x50, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x4b, 0x0a, 0x16, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x52,
	0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x4c, 0x0a, 0x17, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x49, 0x50, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x52, 0x06, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x9c, 0x01, 0x0a, 0x16, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x49, 0x50, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x31, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x52, 0x06, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x12, 0x3b, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x6d, 0x61,
	0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x4d, 0x61, 0x73, 0x6b, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x73, 0x6b,
	0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04,
	0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x4c, 0x0a, 0x17, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50,
	0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x31, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x22, 0x28, 0x0a, 0x16, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x73, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x19, 0x0a, 0x17,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x28, 0x0a, 0x16, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x49, 0x50, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x19, 0x0a, 0x17, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x73, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa2, 0x06, 0x0a,
	0x09, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x73, 0x12, 0x79, 0x0a, 0x04, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x25, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x49, 0x50, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x22, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1c, 0x12, 0x1a, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x5f, 0x69, 0x70, 0x73, 0x12, 0x83, 0x01, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x24, 0x2e,
	0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x73, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2f, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x29, 0x62, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1f, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x5f, 0x69, 0x70, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x8f, 0x01, 0x0a, 0x06,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x27, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49,
	0x50, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x28, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x32, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x2c, 0x3a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x62, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x22, 0x1a, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f,
	0x76, 0x31, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x69, 0x70, 0x73, 0x12, 0x9b, 0x01,
	0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x27, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x49, 0x50, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x28, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x73, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3e, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x38, 0x3a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x62, 0x06, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x32, 0x26, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x69, 0x70, 0x73, 0x2f,
	0x7b, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x69, 0x64, 0x7d, 0x12, 0x84, 0x01, 0x0a, 0x06,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x27, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49,
	0x50, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x28, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x27, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x21, 0x2a, 0x1f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f,
	0x76, 0x31, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x69, 0x70, 0x73, 0x2f, 0x7b, 0x69,
	0x64, 0x7d, 0x12, 0x5d, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x27, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50,
	0x73, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0xda, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x15, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x49, 0x70, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f,
	0x73, 0x61, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6f, 0x73, 0x61, 0x63,
	0x2d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x76, 0x31,
	0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63, 0x5c,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x4f, 0x73,
	0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47,
	0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x4f, 0x73, 0x61,
	0x63, 0x3a, 0x3a, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_private_v1_public_ips_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_osac_private_v1_public_ips_service_proto_goTypes = []any{
	(*PublicIPsListRequest)(nil),    // 0: osac.private.v1.PublicIPsListRequest
	(*PublicIPsListResponse)(nil),   // 1: osac.private.v1.PublicIPsListResponse
	(*PublicIPsGetRequest)(nil),     // 2: osac.private.v1.PublicIPsGetRequest
	(*PublicIPsGetResponse)(nil),    // 3: osac.private.v1.PublicIPsGetResponse
	(*PublicIPsCreateRequest)(nil),  // 4: osac.private.v1.PublicIPsCreateRequest
	(*PublicIPsCreateResponse)(nil), // 5: osac.private.v1.PublicIPsCreateResponse
	(*PublicIPsUpdateRequest)(nil),  // 6: osac.private.v1.PublicIPsUpdateRequest
	(*PublicIPsUpdateResponse)(nil), // 7: osac.private.v1.PublicIPsUpdateResponse
	(*PublicIPsDeleteRequest)(nil),  // 8: osac.private.v1.PublicIPsDeleteRequest
	(*PublicIPsDeleteResponse)(nil), // 9: osac.private.v1.PublicIPsDeleteResponse
	(*PublicIPsSignalRequest)(nil),  // 10: osac.private.v1.PublicIPsSignalRequest
	(*PublicIPsSignalResponse)(nil), // 11: osac.private.v1.PublicIPsSignalResponse
	(*PublicIP)(nil),                // 12: osac.private.v1.PublicIP
	(*fieldmaskpb.FieldMask)(nil),   // 13: google.protobuf.FieldMask
}
var file_osac_private_v1_public_ips_service_proto_depIdxs = []int32{
	12, // 0: osac.private.v1.PublicIPsListResponse.items:type_name -> osac.private.v1.PublicIP
	12, // 1: osac.private.v1.PublicIPsGetResponse.object:type_name -> osac.private.v1.PublicIP
	12, // 2: osac.private.v1.PublicIPsCreateRequest.object:type_name -> osac.private.v1.PublicIP
	12, // 3: osac.private.v1.PublicIPsCreateResponse.object:type_name -> osac.private.v1.PublicIP
	12, // 4: osac.private.v1.PublicIPsUpdateRequest.object:type_name -> osac.private.v1.PublicIP
	13, // 5: osac.private.v1.PublicIPsUpdateRequest.update_mask:type_name -> google.protobuf.FieldMask
	12, // 6: osac.private.v1.PublicIPsUpdateResponse.object:type_name -> osac.private.v1.PublicIP
	0,  // 7: osac.private.v1.PublicIPs.List:input_type -> osac.private.v1.PublicIPsListRequest
	2,  // 8: osac.private.v1.PublicIPs.Get:input_type -> osac.private.v1.PublicIPsGetRequest
	4,  // 9: osac.private.v1.PublicIPs.Create:input_type -> osac.private.v1.PublicIPsCreateRequest
	6,  // 10: osac.private.v1.PublicIPs.Update:input_type -> osac.private.v1.PublicIPsUpdateRequest
	8,  // 11: osac.private.v1.PublicIPs.Delete:input_type -> osac.private.v1.PublicIPsDeleteRequest
	10, // 12: osac.private.v1.PublicIPs.Signal:input_type -> osac.private.v1.PublicIPsSignalRequest
	1,  // 13: osac.private.v1.PublicIPs.List:output_type -> osac.private.v1.PublicIPsListResponse
	3,  // 14: osac.private.v1.PublicIPs.Get:output_type -> osac.private.v1.PublicIPsGetResponse
	5,  // 15: osac.private.v1.PublicIPs.Create:output_type -> osac.private.v1.PublicIPsCreateResponse
	7,  // 16: osac.private.v1.PublicIPs.Update:output_type -> osac.private.v1.PublicIPsUpdateResponse
	9,  // 17: osac.private.v1.PublicIPs.Delete:output_type -> osac.private.v1.PublicIPsDeleteResponse
	11, // 18: osac.private.v1.PublicIPs.Signal:output_type -> osac.private.v1.PublicIPsSignalResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_osac_private_v1_public_ips_service_proto_init() }
func file_osac_private_v1_public_ips_service_proto_init() {
	if File_osac_private_v1_public_ips_service_proto != nil {
		return
	}
	file_osac_private_v1_public_ip_type_proto_init()
	file_osac_private_v1_public_ips_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_public_ips_service_proto_rawDesc), len(file_osac_private_v1_public_ips_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_osac_private_v1_public_ips_service_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_public_ips_service_proto_depIdxs,
		MessageInfos:      file_osac_private_v1_public_ips_service_proto_msgTypes,
	}.Build()
	File_osac_private_v1_public_ips_service_proto = out.File
	file_osac_private_v1_public_ips_service_proto_goTypes = nil
	file_osac_private_v1_public_ips_service_proto_depIdxs = nil
}
