//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/public_ip_pool_type.proto

//go:build protoopaque

package privatev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IP address family for a PublicIPPool.
type IPFamily int32

const (
	// IP family is unknown or has not been specified.
	IPFamily_IP_FAMILY_UNSPECIFIED IPFamily = 0
	// IPv4 address family. CIDRs must be valid IPv4 CIDR notation.
	IPFamily_IP_FAMILY_IPV4 IPFamily = 1
	// IPv6 address family. CIDRs must be valid IPv6 CIDR notation.
	IPFamily_IP_FAMILY_IPV6 IPFamily = 2
)

// Enum value maps for IPFamily.
var (
	IPFamily_name = map[int32]string{
		0: "IP_FAMILY_UNSPECIFIED",
		1: "IP_FAMILY_IPV4",
		2: "IP_FAMILY_IPV6",
	}
	IPFamily_value = map[string]int32{
		"IP_FAMILY_UNSPECIFIED": 0,
		"IP_FAMILY_IPV4":        1,
		"IP_FAMILY_IPV6":        2,
	}
)

func (x IPFamily) Enum() *IPFamily {
	p := new(IPFamily)
	*p = x
	return p
}

func (x IPFamily) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IPFamily) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_private_v1_public_ip_pool_type_proto_enumTypes[0].Descriptor()
}

func (IPFamily) Type() protoreflect.EnumType {
	return &file_osac_private_v1_public_ip_pool_type_proto_enumTypes[0]
}

func (x IPFamily) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Lifecycle states for PublicIPPool resources.
//
// State transitions typically follow: UNSPECIFIED -> PENDING -> READY, with FAILED as a terminal
// error state that may require user intervention or resource recreation.
//
// The CRD phase "Progressing" maps to PENDING at the proto level. This is consistent with all
// networking resources in the fulfillment-service (VirtualNetwork, Subnet, SecurityGroup,
// NetworkClass, HostClass). PENDING describes user-facing readiness ("not usable yet"), while
// the CRD phase describes controller activity ("reconciliation in progress").
type PublicIPPoolState int32

const (
	// State is unknown or has not been determined yet. Default state before initialization.
	PublicIPPoolState_PUBLIC_IP_POOL_STATE_UNSPECIFIED PublicIPPoolState = 0
	// The pool is being provisioned and is not ready for IP allocation yet.
	//
	// During this state, the system is creating the MetalLB IPAddressPool on the target cluster
	// and configuring L2 advertisement. Maps from CRD phase "Progressing".
	PublicIPPoolState_PUBLIC_IP_POOL_STATE_PENDING PublicIPPoolState = 1
	// The pool is fully operational and ready for PublicIP allocation.
	//
	// MetalLB IPAddressPool is configured and L2 advertisement is active. PublicIPs can be
	// allocated from this pool's CIDR ranges. Maps from CRD phase "Ready".
	PublicIPPoolState_PUBLIC_IP_POOL_STATE_READY PublicIPPoolState = 2
	// The pool provisioning has failed.
	//
	// The status.message field contains error details. Common causes include MetalLB configuration
	// errors or cluster connectivity issues. Maps from CRD phase "Failed".
	PublicIPPoolState_PUBLIC_IP_POOL_STATE_FAILED PublicIPPoolState = 3
	// The pool is being deleted.
	//
	// During this state, the system is removing the MetalLB IPAddressPool and cleaning up
	// cluster resources. Deletion is rejected if allocated PublicIPs still reference this pool.
	// Maps from CRD phase "Deleting".
	PublicIPPoolState_PUBLIC_IP_POOL_STATE_DELETING PublicIPPoolState = 4
	// The pool deletion has failed.
	//
	// The deprovision operation encountered an error and could not complete. The status.message
	// field contains error details. Manual intervention may be required before retrying deletion.
	// No CRD phase equivalent (follows the Subnet pattern for proto-level tracking).
	PublicIPPoolState_PUBLIC_IP_POOL_STATE_DELETE_FAILED PublicIPPoolState = 5
)

// Enum value maps for PublicIPPoolState.
var (
	PublicIPPoolState_name = map[int32]string{
		0: "PUBLIC_IP_POOL_STATE_UNSPECIFIED",
		1: "PUBLIC_IP_POOL_STATE_PENDING",
		2: "PUBLIC_IP_POOL_STATE_READY",
		3: "PUBLIC_IP_POOL_STATE_FAILED",
		4: "PUBLIC_IP_POOL_STATE_DELETING",
		5: "PUBLIC_IP_POOL_STATE_DELETE_FAILED",
	}
	PublicIPPoolState_value = map[string]int32{
		"PUBLIC_IP_POOL_STATE_UNSPECIFIED":   0,
		"PUBLIC_IP_POOL_STATE_PENDING":       1,
		"PUBLIC_IP_POOL_STATE_READY":         2,
		"PUBLIC_IP_POOL_STATE_FAILED":        3,
		"PUBLIC_IP_POOL_STATE_DELETING":      4,
		"PUBLIC_IP_POOL_STATE_DELETE_FAILED": 5,
	}
)

func (x PublicIPPoolState) Enum() *PublicIPPoolState {
	p := new(PublicIPPoolState)
	*p = x
	return p
}

func (x PublicIPPoolState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublicIPPoolState) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_private_v1_public_ip_pool_type_proto_enumTypes[1].Descriptor()
}

func (PublicIPPoolState) Type() protoreflect.EnumType {
	return &file_osac_private_v1_public_ip_pool_type_proto_enumTypes[1]
}

func (x PublicIPPoolState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Represents a pool of public IP addresses available for allocation to compute instances.
//
// Each PublicIPPool supports a single IP family (IPv4 or IPv6). The pool contains one or more CIDR
// ranges from which individual PublicIP addresses are allocated. Pools are provider-managed
// resources created by administrators through the private API.
//
// The implementation_strategy field determines how IPs from this pool are advertised on the target
// cluster (e.g., MetalLB L2 mode). This field is set by the system and is not user-configurable.
//
// Capacity tracking fields in the status (total, allocated, available) reflect the current utilization
// of the pool across all its CIDR ranges.
type PublicIPPool struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id       string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Metadata *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3"`
	xxx_hidden_Spec     *PublicIPPoolSpec      `protobuf:"bytes,3,opt,name=spec,proto3"`
	xxx_hidden_Status   *PublicIPPoolStatus    `protobuf:"bytes,4,opt,name=status,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PublicIPPool) Reset() {
	*x = PublicIPPool{}
	mi := &file_osac_private_v1_public_ip_pool_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPPool) ProtoMessage() {}

func (x *PublicIPPool) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_public_ip_pool_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicIPPool) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *PublicIPPool) GetMetadata() *Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *PublicIPPool) GetSpec() *PublicIPPoolSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *PublicIPPool) GetStatus() *PublicIPPoolStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *PublicIPPool) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *PublicIPPool) SetMetadata(v *Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *PublicIPPool) SetSpec(v *PublicIPPoolSpec) {
	x.xxx_hidden_Spec = v
}

func (x *PublicIPPool) SetStatus(v *PublicIPPoolStatus) {
	x.xxx_hidden_Status = v
}

func (x *PublicIPPool) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *PublicIPPool) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *PublicIPPool) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *PublicIPPool) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *PublicIPPool) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *PublicIPPool) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type PublicIPPool_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the public IP pool.
	Id string
	// Metadata of the public IP pool, including name, labels, and timestamps.
	Metadata *Metadata
	// Desired configuration of the public IP pool (admin-specified).
	Spec *PublicIPPoolSpec
	// Current state of the public IP pool (system-provided, read-only).
	Status *PublicIPPoolStatus
}

func (b0 PublicIPPool_builder) Build() *PublicIPPool {
	m0 := &PublicIPPool{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

// Defines the desired configuration for a PublicIPPool.
//
// All spec fields are immutable after creation. To change CIDRs, delete the pool and create a
// new one. The Update RPC only allows metadata changes (name, labels, annotations).
type PublicIPPoolSpec struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cidrs                  []string               `protobuf:"bytes,2,rep,name=cidrs,proto3"`
	xxx_hidden_IpFamily               IPFamily               `protobuf:"varint,3,opt,name=ip_family,json=ipFamily,proto3,enum=osac.private.v1.IPFamily"`
	xxx_hidden_ImplementationStrategy string                 `protobuf:"bytes,4,opt,name=implementation_strategy,json=implementationStrategy,proto3"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *PublicIPPoolSpec) Reset() {
	*x = PublicIPPoolSpec{}
	mi := &file_osac_private_v1_public_ip_pool_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPPoolSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPPoolSpec) ProtoMessage() {}

func (x *PublicIPPoolSpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_public_ip_pool_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicIPPoolSpec) GetCidrs() []string {
	if x != nil {
		return x.xxx_hidden_Cidrs
	}
	return nil
}

func (x *PublicIPPoolSpec) GetIpFamily() IPFamily {
	if x != nil {
		return x.xxx_hidden_IpFamily
	}
	return IPFamily_IP_FAMILY_UNSPECIFIED
}

func (x *PublicIPPoolSpec) GetImplementationStrategy() string {
	if x != nil {
		return x.xxx_hidden_ImplementationStrategy
	}
	return ""
}

func (x *PublicIPPoolSpec) SetCidrs(v []string) {
	x.xxx_hidden_Cidrs = v
}

func (x *PublicIPPoolSpec) SetIpFamily(v IPFamily) {
	x.xxx_hidden_IpFamily = v
}

func (x *PublicIPPoolSpec) SetImplementationStrategy(v string) {
	x.xxx_hidden_ImplementationStrategy = v
}

type PublicIPPoolSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// CIDR ranges for this pool. Required and immutable after creation.
	//
	// Each entry must be valid CIDR notation matching the declared ip_family. All CIDRs must be
	// the same IP family. CIDRs must not overlap with CIDRs in other pools.
	//
	// Example (IPv4): ["192.168.1.0/24", "10.0.5.0/28"]
	// Example (IPv6): ["2001:db8::/64"]
	Cidrs []string
	// IP address family for this pool. Required and immutable after creation.
	//
	// Determines whether the CIDRs in this pool are IPv4 or IPv6. All CIDRs must match this
	// family. A single pool cannot mix IPv4 and IPv6 ranges.
	IpFamily IPFamily
	// Backend strategy used to advertise IPs from this pool on the target cluster.
	//
	// Set by the system based on cluster configuration. Not user-configurable. Currently the
	// only supported strategy is "metallb-l2" (MetalLB Layer 2 advertisement mode).
	ImplementationStrategy string
}

func (b0 PublicIPPoolSpec_builder) Build() *PublicIPPoolSpec {
	m0 := &PublicIPPoolSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Cidrs = b.Cidrs
	x.xxx_hidden_IpFamily = b.IpFamily
	x.xxx_hidden_ImplementationStrategy = b.ImplementationStrategy
	return m0
}

// Represents the current operational state of a PublicIPPool.
//
// Status is system-provided and read-only. Users cannot modify status fields directly; the system
// updates them based on reconciliation of the spec and feedback from the cluster controller.
type PublicIPPoolStatus struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_State       PublicIPPoolState      `protobuf:"varint,1,opt,name=state,proto3,enum=osac.private.v1.PublicIPPoolState"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof"`
	xxx_hidden_Hub         string                 `protobuf:"bytes,3,opt,name=hub,proto3"`
	xxx_hidden_Total       int64                  `protobuf:"varint,4,opt,name=total,proto3"`
	xxx_hidden_Allocated   int64                  `protobuf:"varint,5,opt,name=allocated,proto3"`
	xxx_hidden_Available   int64                  `protobuf:"varint,6,opt,name=available,proto3"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PublicIPPoolStatus) Reset() {
	*x = PublicIPPoolStatus{}
	mi := &file_osac_private_v1_public_ip_pool_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIPPoolStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIPPoolStatus) ProtoMessage() {}

func (x *PublicIPPoolStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_public_ip_pool_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PublicIPPoolStatus) GetState() PublicIPPoolState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return PublicIPPoolState_PUBLIC_IP_POOL_STATE_UNSPECIFIED
}

func (x *PublicIPPoolStatus) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *PublicIPPoolStatus) GetHub() string {
	if x != nil {
		return x.xxx_hidden_Hub
	}
	return ""
}

func (x *PublicIPPoolStatus) GetTotal() int64 {
	if x != nil {
		return x.xxx_hidden_Total
	}
	return 0
}

func (x *PublicIPPoolStatus) GetAllocated() int64 {
	if x != nil {
		return x.xxx_hidden_Allocated
	}
	return 0
}

func (x *PublicIPPoolStatus) GetAvailable() int64 {
	if x != nil {
		return x.xxx_hidden_Available
	}
	return 0
}

func (x *PublicIPPoolStatus) SetState(v PublicIPPoolState) {
	x.xxx_hidden_State = v
}

func (x *PublicIPPoolStatus) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *PublicIPPoolStatus) SetHub(v string) {
	x.xxx_hidden_Hub = v
}

func (x *PublicIPPoolStatus) SetTotal(v int64) {
	x.xxx_hidden_Total = v
}

func (x *PublicIPPoolStatus) SetAllocated(v int64) {
	x.xxx_hidden_Allocated = v
}

func (x *PublicIPPoolStatus) SetAvailable(v int64) {
	x.xxx_hidden_Available = v
}

func (x *PublicIPPoolStatus) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *PublicIPPoolStatus) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

type PublicIPPoolStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Current lifecycle state of the public IP pool.
	State PublicIPPoolState
	// Human-readable message providing additional details about the current state.
	//
	// For PENDING state, may contain progress information like "Waiting for MetalLB configuration".
	// For FAILED state, contains error details. For READY state, typically empty.
	Message *string
	// Identifier of the hub cluster that this pool is deployed to.
	//
	// Set by the fulfillment-service controller when reconciling the pool to a Kubernetes CR on
	// the target hub cluster. Used for tracking which cluster the pool resources reside on.
	Hub string
	// Total number of usable IP addresses across all CIDRs in this pool.
	//
	// Calculated from the CIDR ranges (e.g., a /24 IPv4 CIDR yields 254 usable addresses,
	// excluding network and broadcast addresses). Uses int64 to accommodate large IPv6 CIDR
	// ranges whose address counts exceed int32 capacity.
	Total int64
	// Number of IP addresses currently allocated to PublicIP resources from this pool.
	Allocated int64
	// Number of IP addresses available for new allocations from this pool.
	//
	// Equal to total minus allocated.
	Available int64
}

func (b0 PublicIPPoolStatus_builder) Build() *PublicIPPoolStatus {
	m0 := &PublicIPPoolStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_State = b.State
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Message = b.Message
	}
	x.xxx_hidden_Hub = b.Hub
	x.xxx_hidden_Total = b.Total
	x.xxx_hidden_Allocated = b.Allocated
	x.xxx_hidden_Available = b.Available
	return m0
}

var File_osac_private_v1_public_ip_pool_type_proto protoreflect.FileDescriptor

var file_osac_private_v1_public_ip_pool_type_proto_rawDesc = string([]byte{
	0x0a, 0x29, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x69, 0x70, 0x5f, 0x70, 0x6f, 0x6f, 0x6c,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x73, 0x61,
	0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x62,
	0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x23, 0x6f,
	0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xc9, 0x01, 0x0a, 0x0c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x50,
	0x6f, 0x6f, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x04, 0x73, 0x70,
	0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x49, 0x50, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65,
	0x63, 0x12, 0x3b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x50, 0x6f, 0x6f, 0x6c,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xb1,
	0x01, 0x0a, 0x10, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x50, 0x6f, 0x6f, 0x6c, 0x53,
	0x70, 0x65, 0x63, 0x12, 0x1c, 0x0a, 0x05, 0x63, 0x69, 0x64, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x42, 0x06, 0xe0, 0x41, 0x02, 0xe0, 0x41, 0x05, 0x52, 0x05, 0x63, 0x69, 0x64, 0x72,
	0x73, 0x12, 0x3e, 0x0a, 0x09, 0x69, 0x70, 0x5f, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x50, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x42,
	0x06, 0xe0, 0x41, 0x02, 0xe0, 0x41, 0x05, 0x52, 0x08, 0x69, 0x70, 0x46, 0x61, 0x6d, 0x69, 0x6c,
	0x79, 0x12, 0x3f, 0x0a, 0x17, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x06, 0xe0, 0x41, 0x03, 0xe0, 0x41, 0x05, 0x52, 0x16, 0x69, 0x6d, 0x70, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65,
	0x67, 0x79, 0x22, 0xdd, 0x01, 0x0a, 0x12, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x50,
	0x6f, 0x6f, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x38, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x49, 0x50, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x10, 0x0a, 0x03, 0x68, 0x75, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x68, 0x75, 0x62, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6c,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61,
	0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2a, 0x4d, 0x0a, 0x08, 0x49, 0x50, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x19,
	0x0a, 0x15, 0x49, 0x50, 0x5f, 0x46, 0x41, 0x4d, 0x49, 0x4c, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x50, 0x5f,
	0x46, 0x41, 0x4d, 0x49, 0x4c, 0x59, 0x5f, 0x49, 0x50, 0x56, 0x34, 0x10, 0x01, 0x12, 0x12, 0x0a,
	0x0e, 0x49, 0x50, 0x5f, 0x46, 0x41, 0x4d, 0x49, 0x4c, 0x59, 0x5f, 0x49, 0x50, 0x56, 0x36, 0x10,
	0x02, 0x2a, 0xe7, 0x01, 0x0a, 0x11, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x50, 0x50, 0x6f,
	0x6f, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x24, 0x0a, 0x20, 0x50, 0x55, 0x42, 0x4c, 0x49,
	0x43, 0x5f, 0x49, 0x50, 0x5f, 0x50, 0x4f, 0x4f, 0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x20, 0x0a,
	0x1c, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x5f, 0x49, 0x50, 0x5f, 0x50, 0x4f, 0x4f, 0x4c, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12,
	0x1e, 0x0a, 0x1a, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x5f, 0x49, 0x50, 0x5f, 0x50, 0x4f, 0x4f,
	0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x02, 0x12,
	0x1f, 0x0a, 0x1b, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x5f, 0x49, 0x50, 0x5f, 0x50, 0x4f, 0x4f,
	0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03,
	0x12, 0x21, 0x0a, 0x1d, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x5f, 0x49, 0x50, 0x5f, 0x50, 0x4f,
	0x4f, 0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x49, 0x4e,
	0x47, 0x10, 0x04, 0x12, 0x26, 0x0a, 0x22, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x5f, 0x49, 0x50,
	0x5f, 0x50, 0x4f, 0x4f, 0x4c, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x44, 0x45, 0x4c, 0x45,
	0x54, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x05, 0x42, 0xda, 0x01, 0x0a, 0x13,
	0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2e, 0x76, 0x31, 0x42, 0x15, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x70, 0x50, 0x6f, 0x6f,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4c, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31,
	0x3b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58,
	0xaa, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e,
	0x56, 0x31, 0xca, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_private_v1_public_ip_pool_type_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_osac_private_v1_public_ip_pool_type_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_osac_private_v1_public_ip_pool_type_proto_goTypes = []any{
	(IPFamily)(0),              // 0: osac.private.v1.IPFamily
	(PublicIPPoolState)(0),     // 1: osac.private.v1.PublicIPPoolState
	(*PublicIPPool)(nil),       // 2: osac.private.v1.PublicIPPool
	(*PublicIPPoolSpec)(nil),   // 3: osac.private.v1.PublicIPPoolSpec
	(*PublicIPPoolStatus)(nil), // 4: osac.private.v1.PublicIPPoolStatus
	(*Metadata)(nil),           // 5: osac.private.v1.Metadata
}
var file_osac_private_v1_public_ip_pool_type_proto_depIdxs = []int32{
	5, // 0: osac.private.v1.PublicIPPool.metadata:type_name -> osac.private.v1.Metadata
	3, // 1: osac.private.v1.PublicIPPool.spec:type_name -> osac.private.v1.PublicIPPoolSpec
	4, // 2: osac.private.v1.PublicIPPool.status:type_name -> osac.private.v1.PublicIPPoolStatus
	0, // 3: osac.private.v1.PublicIPPoolSpec.ip_family:type_name -> osac.private.v1.IPFamily
	1, // 4: osac.private.v1.PublicIPPoolStatus.state:type_name -> osac.private.v1.PublicIPPoolState
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_osac_private_v1_public_ip_pool_type_proto_init() }
func file_osac_private_v1_public_ip_pool_type_proto_init() {
	if File_osac_private_v1_public_ip_pool_type_proto != nil {
		return
	}
	file_osac_private_v1_metadata_type_proto_init()
	file_osac_private_v1_public_ip_pool_type_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_public_ip_pool_type_proto_rawDesc), len(file_osac_private_v1_public_ip_pool_type_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_private_v1_public_ip_pool_type_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_public_ip_pool_type_proto_depIdxs,
		EnumInfos:         file_osac_private_v1_public_ip_pool_type_proto_enumTypes,
		MessageInfos:      file_osac_private_v1_public_ip_pool_type_proto_msgTypes,
	}.Build()
	File_osac_private_v1_public_ip_pool_type_proto = out.File
	file_osac_private_v1_public_ip_pool_type_proto_goTypes = nil
	file_osac_private_v1_public_ip_pool_type_proto_depIdxs = nil
}
