//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/private/v1/public_ip_pools_service.proto

package privatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PublicIPPools_List_FullMethodName   = "/osac.private.v1.PublicIPPools/List"
	PublicIPPools_Get_FullMethodName    = "/osac.private.v1.PublicIPPools/Get"
	PublicIPPools_Create_FullMethodName = "/osac.private.v1.PublicIPPools/Create"
	PublicIPPools_Update_FullMethodName = "/osac.private.v1.PublicIPPools/Update"
	PublicIPPools_Delete_FullMethodName = "/osac.private.v1.PublicIPPools/Delete"
	PublicIPPools_Signal_FullMethodName = "/osac.private.v1.PublicIPPools/Signal"
)

// PublicIPPoolsClient is the client API for PublicIPPools service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublicIPPoolsClient interface {
	// Retrieves the list of public IP pools.
	List(ctx context.Context, in *PublicIPPoolsListRequest, opts ...grpc.CallOption) (*PublicIPPoolsListResponse, error)
	// Retrieves the details of one specific public IP pool.
	Get(ctx context.Context, in *PublicIPPoolsGetRequest, opts ...grpc.CallOption) (*PublicIPPoolsGetResponse, error)
	// Creates a new public IP pool.
	Create(ctx context.Context, in *PublicIPPoolsCreateRequest, opts ...grpc.CallOption) (*PublicIPPoolsCreateResponse, error)
	// Updates an existing public IP pool. Only metadata fields (name, labels, annotations) are mutable.
	// All spec fields (cidrs, ip_family, implementation_strategy) are immutable after creation.
	Update(ctx context.Context, in *PublicIPPoolsUpdateRequest, opts ...grpc.CallOption) (*PublicIPPoolsUpdateResponse, error)
	// Deletes a public IP pool. Rejected if allocated PublicIPs still reference this pool.
	Delete(ctx context.Context, in *PublicIPPoolsDeleteRequest, opts ...grpc.CallOption) (*PublicIPPoolsDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(ctx context.Context, in *PublicIPPoolsSignalRequest, opts ...grpc.CallOption) (*PublicIPPoolsSignalResponse, error)
}

type publicIPPoolsClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicIPPoolsClient(cc grpc.ClientConnInterface) PublicIPPoolsClient {
	return &publicIPPoolsClient{cc}
}

func (c *publicIPPoolsClient) List(ctx context.Context, in *PublicIPPoolsListRequest, opts ...grpc.CallOption) (*PublicIPPoolsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicIPPoolsListResponse)
	err := c.cc.Invoke(ctx, PublicIPPools_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicIPPoolsClient) Get(ctx context.Context, in *PublicIPPoolsGetRequest, opts ...grpc.CallOption) (*PublicIPPoolsGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicIPPoolsGetResponse)
	err := c.cc.Invoke(ctx, PublicIPPools_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicIPPoolsClient) Create(ctx context.Context, in *PublicIPPoolsCreateRequest, opts ...grpc.CallOption) (*PublicIPPoolsCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicIPPoolsCreateResponse)
	err := c.cc.Invoke(ctx, PublicIPPools_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicIPPoolsClient) Update(ctx context.Context, in *PublicIPPoolsUpdateRequest, opts ...grpc.CallOption) (*PublicIPPoolsUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicIPPoolsUpdateResponse)
	err := c.cc.Invoke(ctx, PublicIPPools_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicIPPoolsClient) Delete(ctx context.Context, in *PublicIPPoolsDeleteRequest, opts ...grpc.CallOption) (*PublicIPPoolsDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicIPPoolsDeleteResponse)
	err := c.cc.Invoke(ctx, PublicIPPools_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicIPPoolsClient) Signal(ctx context.Context, in *PublicIPPoolsSignalRequest, opts ...grpc.CallOption) (*PublicIPPoolsSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicIPPoolsSignalResponse)
	err := c.cc.Invoke(ctx, PublicIPPools_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicIPPoolsServer is the server API for PublicIPPools service.
// All implementations must embed UnimplementedPublicIPPoolsServer
// for forward compatibility.
type PublicIPPoolsServer interface {
	// Retrieves the list of public IP pools.
	List(context.Context, *PublicIPPoolsListRequest) (*PublicIPPoolsListResponse, error)
	// Retrieves the details of one specific public IP pool.
	Get(context.Context, *PublicIPPoolsGetRequest) (*PublicIPPoolsGetResponse, error)
	// Creates a new public IP pool.
	Create(context.Context, *PublicIPPoolsCreateRequest) (*PublicIPPoolsCreateResponse, error)
	// Updates an existing public IP pool. Only metadata fields (name, labels, annotations) are mutable.
	// All spec fields (cidrs, ip_family, implementation_strategy) are immutable after creation.
	Update(context.Context, *PublicIPPoolsUpdateRequest) (*PublicIPPoolsUpdateResponse, error)
	// Deletes a public IP pool. Rejected if allocated PublicIPs still reference this pool.
	Delete(context.Context, *PublicIPPoolsDeleteRequest) (*PublicIPPoolsDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(context.Context, *PublicIPPoolsSignalRequest) (*PublicIPPoolsSignalResponse, error)
	mustEmbedUnimplementedPublicIPPoolsServer()
}

// UnimplementedPublicIPPoolsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPublicIPPoolsServer struct{}

func (UnimplementedPublicIPPoolsServer) List(context.Context, *PublicIPPoolsListRequest) (*PublicIPPoolsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedPublicIPPoolsServer) Get(context.Context, *PublicIPPoolsGetRequest) (*PublicIPPoolsGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedPublicIPPoolsServer) Create(context.Context, *PublicIPPoolsCreateRequest) (*PublicIPPoolsCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPublicIPPoolsServer) Update(context.Context, *PublicIPPoolsUpdateRequest) (*PublicIPPoolsUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedPublicIPPoolsServer) Delete(context.Context, *PublicIPPoolsDeleteRequest) (*PublicIPPoolsDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedPublicIPPoolsServer) Signal(context.Context, *PublicIPPoolsSignalRequest) (*PublicIPPoolsSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedPublicIPPoolsServer) mustEmbedUnimplementedPublicIPPoolsServer() {}
func (UnimplementedPublicIPPoolsServer) testEmbeddedByValue()                       {}

// UnsafePublicIPPoolsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicIPPoolsServer will
// result in compilation errors.
type UnsafePublicIPPoolsServer interface {
	mustEmbedUnimplementedPublicIPPoolsServer()
}

func RegisterPublicIPPoolsServer(s grpc.ServiceRegistrar, srv PublicIPPoolsServer) {
	// If the following call pancis, it indicates UnimplementedPublicIPPoolsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PublicIPPools_ServiceDesc, srv)
}

func _PublicIPPools_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicIPPoolsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicIPPoolsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicIPPools_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicIPPoolsServer).List(ctx, req.(*PublicIPPoolsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicIPPools_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicIPPoolsGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicIPPoolsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicIPPools_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicIPPoolsServer).Get(ctx, req.(*PublicIPPoolsGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicIPPools_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicIPPoolsCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicIPPoolsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicIPPools_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicIPPoolsServer).Create(ctx, req.(*PublicIPPoolsCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicIPPools_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicIPPoolsUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicIPPoolsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicIPPools_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicIPPoolsServer).Update(ctx, req.(*PublicIPPoolsUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicIPPools_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicIPPoolsDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicIPPoolsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicIPPools_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicIPPoolsServer).Delete(ctx, req.(*PublicIPPoolsDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicIPPools_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicIPPoolsSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicIPPoolsServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicIPPools_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicIPPoolsServer).Signal(ctx, req.(*PublicIPPoolsSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PublicIPPools_ServiceDesc is the grpc.ServiceDesc for PublicIPPools service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublicIPPools_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.private.v1.PublicIPPools",
	HandlerType: (*PublicIPPoolsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _PublicIPPools_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _PublicIPPools_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _PublicIPPools_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PublicIPPools_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PublicIPPools_Delete_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _PublicIPPools_Signal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/private/v1/public_ip_pools_service.proto",
}
