//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/private/v1/public_ips_service.proto

package privatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PublicIPs_List_FullMethodName   = "/osac.private.v1.PublicIPs/List"
	PublicIPs_Get_FullMethodName    = "/osac.private.v1.PublicIPs/Get"
	PublicIPs_Create_FullMethodName = "/osac.private.v1.PublicIPs/Create"
	PublicIPs_Update_FullMethodName = "/osac.private.v1.PublicIPs/Update"
	PublicIPs_Delete_FullMethodName = "/osac.private.v1.PublicIPs/Delete"
	PublicIPs_Signal_FullMethodName = "/osac.private.v1.PublicIPs/Signal"
)

// PublicIPsClient is the client API for PublicIPs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublicIPsClient interface {
	// Retrieves the list of public IPs.
	List(ctx context.Context, in *PublicIPsListRequest, opts ...grpc.CallOption) (*PublicIPsListResponse, error)
	// Retrieves the details of one specific public IP.
	Get(ctx context.Context, in *PublicIPsGetRequest, opts ...grpc.CallOption) (*PublicIPsGetResponse, error)
	// Creates a new public IP. The spec.pool field determines which PublicIPPool the address is allocated from.
	Create(ctx context.Context, in *PublicIPsCreateRequest, opts ...grpc.CallOption) (*PublicIPsCreateResponse, error)
	// Updates an existing public IP. The spec.pool field is immutable; only metadata and compute_instance can change.
	Update(ctx context.Context, in *PublicIPsUpdateRequest, opts ...grpc.CallOption) (*PublicIPsUpdateResponse, error)
	// Deletes a public IP. The allocated address is returned to the parent pool's available capacity.
	Delete(ctx context.Context, in *PublicIPsDeleteRequest, opts ...grpc.CallOption) (*PublicIPsDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(ctx context.Context, in *PublicIPsSignalRequest, opts ...grpc.CallOption) (*PublicIPsSignalResponse, error)
}

type publicIPsClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicIPsClient(cc grpc.ClientConnInterface) PublicIPsClient {
	return &publicIPsClient{cc}
}

func (c *publicIPsClient) List(ctx context.Context, in *PublicIPsListRequest, opts ...grpc.CallOption) (*PublicIPsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicIPsListResponse)
	err := c.cc.Invoke(ctx, PublicIPs_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicIPsClient) Get(ctx context.Context, in *PublicIPsGetRequest, opts ...grpc.CallOption) (*PublicIPsGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicIPsGetResponse)
	err := c.cc.Invoke(ctx, PublicIPs_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicIPsClient) Create(ctx context.Context, in *PublicIPsCreateRequest, opts ...grpc.CallOption) (*PublicIPsCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicIPsCreateResponse)
	err := c.cc.Invoke(ctx, PublicIPs_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicIPsClient) Update(ctx context.Context, in *PublicIPsUpdateRequest, opts ...grpc.CallOption) (*PublicIPsUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicIPsUpdateResponse)
	err := c.cc.Invoke(ctx, PublicIPs_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicIPsClient) Delete(ctx context.Context, in *PublicIPsDeleteRequest, opts ...grpc.CallOption) (*PublicIPsDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicIPsDeleteResponse)
	err := c.cc.Invoke(ctx, PublicIPs_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicIPsClient) Signal(ctx context.Context, in *PublicIPsSignalRequest, opts ...grpc.CallOption) (*PublicIPsSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicIPsSignalResponse)
	err := c.cc.Invoke(ctx, PublicIPs_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicIPsServer is the server API for PublicIPs service.
// All implementations must embed UnimplementedPublicIPsServer
// for forward compatibility.
type PublicIPsServer interface {
	// Retrieves the list of public IPs.
	List(context.Context, *PublicIPsListRequest) (*PublicIPsListResponse, error)
	// Retrieves the details of one specific public IP.
	Get(context.Context, *PublicIPsGetRequest) (*PublicIPsGetResponse, error)
	// Creates a new public IP. The spec.pool field determines which PublicIPPool the address is allocated from.
	Create(context.Context, *PublicIPsCreateRequest) (*PublicIPsCreateResponse, error)
	// Updates an existing public IP. The spec.pool field is immutable; only metadata and compute_instance can change.
	Update(context.Context, *PublicIPsUpdateRequest) (*PublicIPsUpdateResponse, error)
	// Deletes a public IP. The allocated address is returned to the parent pool's available capacity.
	Delete(context.Context, *PublicIPsDeleteRequest) (*PublicIPsDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(context.Context, *PublicIPsSignalRequest) (*PublicIPsSignalResponse, error)
	mustEmbedUnimplementedPublicIPsServer()
}

// UnimplementedPublicIPsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPublicIPsServer struct{}

func (UnimplementedPublicIPsServer) List(context.Context, *PublicIPsListRequest) (*PublicIPsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedPublicIPsServer) Get(context.Context, *PublicIPsGetRequest) (*PublicIPsGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedPublicIPsServer) Create(context.Context, *PublicIPsCreateRequest) (*PublicIPsCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPublicIPsServer) Update(context.Context, *PublicIPsUpdateRequest) (*PublicIPsUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedPublicIPsServer) Delete(context.Context, *PublicIPsDeleteRequest) (*PublicIPsDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedPublicIPsServer) Signal(context.Context, *PublicIPsSignalRequest) (*PublicIPsSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedPublicIPsServer) mustEmbedUnimplementedPublicIPsServer() {}
func (UnimplementedPublicIPsServer) testEmbeddedByValue()                   {}

// UnsafePublicIPsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicIPsServer will
// result in compilation errors.
type UnsafePublicIPsServer interface {
	mustEmbedUnimplementedPublicIPsServer()
}

func RegisterPublicIPsServer(s grpc.ServiceRegistrar, srv PublicIPsServer) {
	// If the following call pancis, it indicates UnimplementedPublicIPsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PublicIPs_ServiceDesc, srv)
}

func _PublicIPs_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicIPsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicIPsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicIPs_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicIPsServer).List(ctx, req.(*PublicIPsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicIPs_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicIPsGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicIPsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicIPs_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicIPsServer).Get(ctx, req.(*PublicIPsGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicIPs_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicIPsCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicIPsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicIPs_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicIPsServer).Create(ctx, req.(*PublicIPsCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicIPs_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicIPsUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicIPsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicIPs_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicIPsServer).Update(ctx, req.(*PublicIPsUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicIPs_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicIPsDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicIPsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicIPs_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicIPsServer).Delete(ctx, req.(*PublicIPsDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicIPs_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicIPsSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicIPsServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicIPs_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicIPsServer).Signal(ctx, req.(*PublicIPsSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PublicIPs_ServiceDesc is the grpc.ServiceDesc for PublicIPs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublicIPs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.private.v1.PublicIPs",
	HandlerType: (*PublicIPsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _PublicIPs_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _PublicIPs_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _PublicIPs_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PublicIPs_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PublicIPs_Delete_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _PublicIPs_Signal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/private/v1/public_ips_service.proto",
}
